services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: bankingsystem
      POSTGRES_USER: banking_system
      POSTGRES_PASSWORD: wgZ8W&t6
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: