spring:
  application:
    name: banking-system
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingsystem
    username: banking_system
    password: wgZ8W&t6
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8089
