spring:
  application:
    name: banking-system
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingsystem
    username: bankingsystem
    password: bankingsystem
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8089
